import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRef, useState } from "react";

export default function Home() {
  const [key, setKey] = useState("");

  const fileInputRef = useRef<HTMLInputElement>(null);

  const [uploadFileKey, setUploadFileKey] = useState("");

  const handleReceive = async () => {
    const res = await fetch(
      `http://localhost:3000/api/download/file?key=${key}`,
      {
        method: "GET",
      }
    );

    console.log(res);
  };

  const handleSend = async () => {
    const file = fileInputRef.current?.files?.[0];

    if (!file) {
      return;
    }

    const fileReader = new FileReader();

    fileReader.onload = async (event) => {
      if (!event.target?.result) {
        return;
      }

      const chunk = event.target.result as ArrayBuffer;

      const res = await fetch(
        `http://localhost:3000/api/upload/file?filename=${file.name}&filetype=${file.type}`,
        {
          method: "POST",
          headers: {
            "content-type": "application/octet-stream",
            "content-length": chunk.byteLength.toString(),
          },
          body: chunk,
        }
      );

      const data = await res.json();
      setUploadFileKey(data.key);
    };

    fileReader.readAsArrayBuffer(file);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <input type="file" ref={fileInputRef} />
          {uploadFileKey.length > 0 && <div>{`Key: ${uploadFileKey}`}</div>}
          <button onClick={handleSend}>Send</button>
        </div>
        <div>
          <input
            type="number"
            value={key}
            onChange={(e) => setKey(e.target.value)}
          />
          <button onClick={handleReceive}>
            <a href={`http://localhost:3000/api/download/file?key=${key}`}>
              Receive
            </a>
          </button>
        </div>
      </main>
    </>
  );
}
